# https://taskfile.dev

version: '3'

includes:
  checks: ./taskfiles/Check.yml
  django:
    taskfile: ./taskfiles/Django.yml
    flatten: true
  docker: ./taskfiles/Docker.yml
  lint: ./taskfiles/Lint.yml
  test: ./taskfiles/Test.yml

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list-all

  env:
    desc: "Ensure .env exists (loaded automatically via dotenv). Creates it if does not exist."
    cmds:
      - |
        if [ ! -f .env ]; then
          cp .env.default .env;
          echo "[env] created .env from .env.default";
        fi
    status:
      - test -f .env
